#!/usr/bin/env python3
"""Generate vBot/weapon_data.lua from the 7.72 objects.srv item catalog.

The client .dat has no notion of which SKILL a weapon trains (sword vs club vs
axe vs distance) - that lives in the server-side objects.srv WeaponType /
Bow* / Throw* / Wand* attributes (see decompiled crcombat.cc
WeaponTypeToSkill / GetAttackValue). The 7.72 objects.srv is bundled at the
client root and its TypeIDs match the client item ids, so we bake a small
id -> category table the Skills Training analyzer loads at runtime to figure
out which skill the equipped weapon trains.

Categories emitted:
    sword / club / axe  - melee weapons (WeaponType 1/2/3)
    dist                - bows (BowRange) and throwables (ThrowAttackValue)
    shield              - Shield flag items (train shielding when defending)
    wand                - Wand* items (mana-based, no weapon skill tries)

Usage:
    python3 gen_weapon_data.py [OBJECTS_SRV] [OUT_LUA]

Defaults assume the standard repo layout:
    OBJECTS_SRV = <client root>/objects.srv
    OUT_LUA     = <this dir>/../vBot/weapon_data.lua
"""
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_SRV = os.path.normpath(
    os.path.join(HERE, "..", "..", "..", "..", "..", "objects.srv"))
DEFAULT_OUT = os.path.normpath(os.path.join(HERE, "..", "vBot", "weapon_data.lua"))

# Server enum (decompiled enums.hh): WEAPON_SWORD=1, WEAPON_CLUB=2, WEAPON_AXE=3.
_WEAPON_TYPE_TO_SKILL = {1: "sword", 2: "club", 3: "axe"}


def classify(flags, attrs):
    m = re.search(r"\bWeaponType=(\d+)", attrs)
    if m:
        return _WEAPON_TYPE_TO_SKILL.get(int(m.group(1)))
    if re.search(r"\bShield\b", flags) or "ShieldDefendValue" in attrs:
        return "shield"
    if "BowRange" in attrs or "ThrowAttackValue" in attrs:
        return "dist"
    if "WandRange" in attrs or "WandManaConsumption" in attrs:
        return "wand"
    return None


def main():
    srv_path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRV
    out_path = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_OUT

    with open(srv_path, "r", encoding="latin-1") as f:
        text = f.read()

    entries = []  # (id, category, name)
    # Blocks start at "TypeID = N" and run until the next TypeID.
    blocks = re.split(r"(?m)^TypeID\s*=\s*", text)[1:]
    for block in blocks:
        id_match = re.match(r"(\d+)", block)
        if not id_match:
            continue
        type_id = int(id_match.group(1))
        name_m = re.search(r'(?m)^Name\s*=\s*"([^"]*)"', block)
        flags_m = re.search(r"(?m)^Flags\s*=\s*\{([^}]*)\}", block)
        attrs_m = re.search(r"(?m)^Attributes\s*=\s*\{([^}]*)\}", block)
        category = classify(flags_m.group(1) if flags_m else "",
                            attrs_m.group(1) if attrs_m else "")
        if category:
            entries.append((type_id, category, name_m.group(1) if name_m else ""))

    entries.sort()
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("-- AUTO-GENERATED by tools/gen_weapon_data.py - do not edit by hand.\n")
        f.write("-- Maps 7.72 item id -> weapon category (objects.srv WeaponType et al).\n")
        f.write("-- Used by the Skills Training analyzer to tell which skill the\n")
        f.write("-- equipped weapon trains. Regenerate after changing objects.srv.\n")
        f.write("WeaponData = {\n")
        for type_id, category, name in entries:
            f.write('  [%d] = "%s", -- %s\n' % (type_id, category, name))
        f.write("}\n")

    counts = {}
    for _, category, _ in entries:
        counts[category] = counts.get(category, 0) + 1
    print("wrote %s: %d items %s" % (out_path, len(entries), counts))


if __name__ == "__main__":
    main()
